### ISSUE TITLE
Add tags to all images in the Helm Chart

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides-helm#16]
### Is your feature request related to a specific problem?

Pulls latest which might not be stable

**Comment by RobertKeyser** [comment]
@nicolas-ethyca,  the versions of Fides and the privacy center can be controlled within the `Values.yaml` file as the keys `fides.image.tag` and `privacyCenter.image.tag`:

https://github.com/ethyca/fides-helm/blob/d1e1e86e801e6dcd7f545fb045df9617e164705b/fides/values.yaml#L9
https://github.com/ethyca/fides-helm/blob/d1e1e86e801e6dcd7f545fb045df9617e164705b/fides/values.yaml#L62

If unset, they will both default to the value of the `appVersion` within the `Charts.yaml`. If you wanted to override the tag to another version (or even an entirely different image), you can set all those values in the image keys:

```yaml
  image:
    repository: some-custom/image-repo-fides
    pullPolicy: IfNotPresent
    # Overrides the Fides image tag whose default is the chart appVersion.
    tag: "2.4.0-custom"
```
